### ISSUE TITLE
The url inside the composer.json should be in their secure version?

### ISSUE THREAD

**Issue by S-Tian86** [thephpleague/uri-interfaces#14]
Hi,

I think the url should be written with http:// instead of http://.
https://github.com/thephpleague/uri-interfaces/blob/a8d5dcc768d29905bcc76a2f46ba443029f163d6/composer.json#L11
What do you think?
Regards

**Comment by nyamsprod** [comment]
A PR with the corresponding fix is welcomed

**Comment by S-Tian86** [comment]
Sure, no problem.
