### ISSUE TITLE
PHP 8 support

### ISSUE THREAD

**Issue by someniatko** [thephpleague/uri-interfaces#8]
### Feature Request

|    Q        |   A
|------------ | ------
| New Feature | yes
| BC Break    | no

#### Proposal

A new major version of PHP (8) will be released on November. I think that it would be a good idea to allow ensure compatibility with PHP 8 by this time. For this package, i think, the only change required is allowing it in `composer.json`.

**Comment by nyamsprod** [comment]
@someniatko you are totally right. You could submit a PR for relaxing the composer requirement

**Comment by nyamsprod** [comment]
version 2.2.0 is out thanks for the contribution
